### ISSUE TITLE
[FEATURE] Fireball

### ISSUE THREAD

**Issue by mustachebutter** [mustachebutter/GodotAutoSurvival#14]
## Linked Issues
#11 
#17 
#19 
## What to implement? 
---
- [x] A projectile that shoots from the Player, deal damage on hit and destroy itself afterwards
- [x] A `StatusEffect` that applies `Burn` to the hit character for X seconds
  - [x] When another fireball hits the character, refreshes the debuff
- [x] When the `Burn` damage kills the hit character, explodes and deal damage to all enemies in the surrounding area
  - [x] Consider applying burn to these characters as well (Augment)

**Comment by mustachebutter** [comment]
Needs to reposition the damage number back to original position every time it pops ups to the right of the previous number

**Comment by mustachebutter** [comment]
### Work on the Fireball Explosion of AutoSurvival
- [ ] Get the physics related functions to run
- [ ] Spread the debuffs to all nearby enemies
- [ ] Clear the dead character + VFX after finishing
- [x] Fixing the explosion VFX size
  - Using `Nearest` as a Filtering option for the texture file. Can be changed in the CanvasItem section when selecting on the sprite frame

**Comment by mustachebutter** [comment]
Current suspected problem is that we're applying the effect by using `StatusEffectComponent.ApplyEffectToCharacter` and uses the same Burn instance. But it doesn't make sense because Burn only holds a payload of information regarding the status effect and we're applying the same Burn to different targets.
![image](https://github.com/mustachebutter/GodotAutoSurvival/assets/43947255/e686c05b-3642-437f-8cfe-e7b9933c44fd)
![image](https://github.com/mustachebutter/GodotAutoSurvival/assets/43947255/c633a290-b656-4401-9de4-5b8784d58aee)

**Comment by mustachebutter** [comment]
Fixed! Each status effect has its own timer. So applying the same instance to nearby targets doesn't make sense. Therefore, I created new instances of the Burn and apply to each of the new targets.

**Comment by mustachebutter** [comment]
One problem though, the `ApplySideTargets` still add one single instance of explosion to all of them (essentially reusing the same instance). We need to figure out a better way for `AppltSideTargets` to be in and prevent the error logs

Screenshot:

![image](https://github.com/mustachebutter/GodotAutoSurvival/assets/43947255/4a88dfe3-3ba6-4baf-bd6d-18193751ab51)

**Comment by mustachebutter** [comment]
Fixed. The reason for this error is that `OnTargetDied` got triggered multiple times due to subscribing constantly on every tick of damage of DOT status effect. It is fixed by moving to `StartStatusEffect` which is called once on hitting the effect.
