### ISSUE TITLE
[FEATURE] Zap

### ISSUE THREAD

**Issue by mustachebutter** [mustachebutter/GodotAutoSurvival#20]
## Linked Issues
#11
## What to implement? 
---
- [x] An electric type weapon that, once hit, applies a debuff.
  - [x] After 3 hits, chain lightning between target and enemies
- [x] The first hit will deal initial damage, instantly hit all enemies within a closeby range with reduced damage (imagine Statik shiv from LOL)
- [ ] (Optional) Can apply a "Shocked" state where it freezes the target, rendering them unable to move
