### ISSUE TITLE
[REWORK] Refactor Weapons system

### ISSUE THREAD

**Issue by mustachebutter** [mustachebutter/GodotAutoSurvival#23]
## Linked Issues
#22 
## What to implement? 
Rework weapon system by adding a base class `Weapon` which `Projectile` and `Beam` inherits from. 
- [x] Determines which attributes/properties are common for both classes
- [x] Refactor `Projectile`
- [x] Refactor `Beam`
- [x] Refactor `ProjectileData` -> `WeaponData`
  - [x] Update the importer/parser
  - [x] WeaponComponent needs to be able to switch between these flawlessly
