### ISSUE TITLE
[FEATURE] Add items

### ISSUE THREAD

**Issue by mustachebutter** [mustachebutter/GodotAutoSurvival#36]
## Linked Issues
#35
## What to implement? 
---
- [ ] Add items that have extra effects to the character
- [ ] Can also be upgraded with augments or from save room
- [ ] A different type, consumables, to increase some stats temporarily (for a level) and healing items
